# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0


executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

# Define a job to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment with Maven and OpenJDK.
    docker:
      - image: maven:3.8.6-openjdk-11  # Utiliser Maven avec OpenJDK 11

    # Add steps to the job
    steps:
      # Checkout the code as the first step.
      - checkout

      # Run unit tests with Maven
      - run: mvn test
      - run: mvn test jacoco:report
  example-job:
    docker:
      - image: maven:3.8.6-openjdk-11
    steps:
      - codecov/upload



# Orchestrate jobs using workflows
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Exécuter uniquement sur la branche master
      - example-job

