version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  maven-executor:
    docker:
      - image: maven:3.8.6-openjdk-11

jobs:
  build:
    docker:
      - image: maven:3.8.6-openjdk-11

    steps:
      # 1. Récupérer le code
      - checkout

      # 2. Nettoyer le projet
      - run: mvn clean

      # 3. Lancer les tests unitaires avec Maven
      - run: mvn test

      # 4. Lancer Checkstyle
      - run: mvn checkstyle:checkstyle

      # 5. Générer le rapport de couverture avec JaCoCo
      - run: mvn jacoco:report

      # 6. Télécharger le rapport de couverture sur Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

      # 7. Installer Python pour générer le badge
      - run:
          name: Install Python
          command: apt-get update && apt-get install -y python3 python3-pip

      # 8. Générer le badge à partir du rapport Checkstyle
      - run:
          name: Generate Badge
          command: python3 generate_badge.py
          environment:
            CHECKSTYLE_REPORT: target/checkstyle-result.xml

      # 9. Déployer le badge sur un service d'hébergement (par exemple, GitHub Pages ou un serveur S3)
      - run:
          name: Deploy Badge
          command: |
            echo "Badge deployment placeholder. Replace with your deployment logic."

      # 10. Conserver le rapport Checkstyle comme artefact
      - store_artifacts:
          path: target/site/checkstyle.html
          destination: checkstyle-report

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
